name: Deployment CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [15.x]
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - run: yarn build && yarn start
