# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: c-hive/gha-npm-cache@v1
      # with:
        # directory: server # Optional, speficy the folder of package-lock.json if not in the root directory
    - name: Install JS dependencies
      run: npm install
    - run: npm run build
    - run: gh-pages -d build
