# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deployment CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [15.x]
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - uses: linchpin/action-build-yarn-npm@master
      # with:
        # directory: server # Optional, speficy the folder of package-lock.json if not in the root directory
    - run: npm install -g gh-pages --save-dev
    - run: sudo yarn install
    - run: sudo rm -rf node_modules/ && npm i
    - run: sudo sysctl fs.inotify.max_user_watches=524288
    - run: sudo sysctl -p
    - run: yarn start
