# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deployment CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: linchpin/action-build-yarn-npm@master
      # with:
        # directory: server # Optional, speficy the folder of package-lock.json if not in the root directory
    - name: Install Deps
    - run: npm install -g gh-pages --save-dev 
    - run: sudo yarn install
    - run: sudo yarn add gh-pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
    - run: sudo yarn start
